spring.application.name=portal
spring.datasource.url=jdbc:mysql://localhost:3306/job_portal
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Jpa/hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=U_--OZagEMUMcUEWsZ7gpnOabqnA4BLTmt6cZ3omC7LbwChP3uvTNeg22uFjWWG_F0QMmEm7RVmScdV3dGYQ7XyYQmr-AnVsX5ByQ3M5rcV1WdQPLp5EtuLKRDw0kiB7HGE3aCoCENjD06cQmeKL9v6pKkNO1W1yAuG5FQKe2wVK7zw7eA42Ro0hJYuQEOyIUjHmTRShTPOxDlxVpH32cRcOzfa-pcQe8bMHDeEQpOBmyYGad3P8MUnXuEuiighG9x753tEZTqHATax_8xx7lcMh0LHW9WBqhOCHtBO5PowfxrLrP9dwLtmVnrrA7NpdGSn5JGP24Yt7fbhj76TyOQ

#application
server.port=8080
# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,env,beans,prometheus,todoStats
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always



# Info Endpoint
info.app.name=Task Manager API
info.app.description=A comprehensive task management system
info.app.version=1.0.0
management.info.env.enabled=true


# Metrics
management.metrics.tags.application=${spring.application.name}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# If using Spring Security, ensure this is enabled
springdoc.show-actuator=true

logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG

# Increase size limits for file uploads/downloads
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# If using Hibernate/JPA with Postgres/MySQL
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
